### ISSUE TITLE
ESP32 C3 support test.

### ISSUE THREAD

**Issue by freemanzwin** [qqqlab/ESP32-SoftWire#1]
Thank you for sharing good data.

If you modify ESP32 C3 like this, there will be no error.
Only examples have been tested.
==================
ESP32_SoftWire.cpp
-------------------------------
#if CONFIG_IDF_TARGET_ESP32C3
#define SDA_HI() GPIO.out_w1ts.val = _sda_mask // Do not drive SDA (set pin high-impedance)
#define SDA_LO() GPIO.out_w1tc.val = _sda_mask // Actively drive SDA signal low
#define SDA_IN() (GPIO.in.val & _sda_mask ? 1 : 0) // Return current level of SCL line, 0 or 1
#define SCL_HI() GPIO.out_w1ts.val = _scl_mask  // Do not drive SCL (set pin high-impedance)
#define SCL_LO() GPIO.out_w1tc.val = _scl_mask // Actively drive SCL signal low
#define SCL_IN() (GPIO.in.val & _scl_mask ? 1 : 0) // Return current level of SCL line, 0 or 1
#else
#define SDA_HI() GPIO.out_w1ts = _sda_mask // Do not drive SDA (set pin high-impedance)
#define SDA_LO() GPIO.out_w1tc = _sda_mask // Actively drive SDA signal low
#define SDA_IN() (GPIO.in & _sda_mask ? 1 : 0) // Return current level of SCL line, 0 or 1
#define SCL_HI() GPIO.out_w1ts = _scl_mask  // Do not drive SCL (set pin high-impedance)
#define SCL_LO() GPIO.out_w1tc = _scl_mask // Actively drive SCL signal low
#define SCL_IN() (GPIO.in & _scl_mask ? 1 : 0) // Return current level of SCL line, 0 or 1
#endif

**Comment by qqqlab** [comment]
Thanks! I've added it to the code and made a new release.
